# Generated by Django 4.2.5 on 2023-09-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
